# Generated by Django 5.2.13 on 2026-05-27 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('level', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(default='query', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Congestion Log',
                'verbose_name_plural': 'Congestion Logs',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('dest_name', models.CharField(max_length=255)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_sec', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('route_geometry', models.JSONField()),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('bus', 'Bus'), ('truck', 'Truck'), ('ambulance', 'Ambulance')], db_index=True, default='car', max_length=50)),
                ('toll_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_model', models.CharField(blank=True, max_length=20, null=True)),
                ('congestion_level', models.CharField(default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TollCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_toll', models.DecimalField(decimal_places=2, max_digits=12)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_toll', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pricing_model', models.CharField(max_length=20)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toll', to='insights.trip')),
            ],
            options={
                'verbose_name': 'Toll Collection',
                'verbose_name_plural': 'Toll Collections',
            },
        ),
        migrations.CreateModel(
            name='RoadCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('condition_type', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('under_construction', 'Under Construction'), ('closed', 'Closed'), ('accident', 'Accident'), ('flooding', 'Flooding'), ('pothole', 'Pothole')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('resolved', 'Resolved')], db_index=True, default='reported', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Road Condition',
                'verbose_name_plural': 'Road Conditions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'condition_type'], name='insights_ro_status_a3f3a1_idx'), models.Index(fields=['lat', 'lng'], name='insights_ro_lat_c7be3e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', '-created_at'], name='insights_tr_user_id_90ef22_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle_type', 'created_at'], name='insights_tr_vehicle_e1e51b_idx'),
        ),
    ]
