# Generated by Django 5.2.13 on 2026-05-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_road_km', models.FloatField(blank=True, null=True)),
                ('surfaced_road_km', models.FloatField(blank=True, null=True)),
                ('nh_km', models.FloatField(blank=True, null=True)),
                ('sh_km', models.FloatField(blank=True, null=True)),
                ('registered_vehicles', models.BigIntegerField(blank=True, null=True)),
                ('revenue_central', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('revenue_state', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Economic Survey',
                'verbose_name_plural': 'Economic Surveys',
            },
        ),
        migrations.CreateModel(
            name='NETCDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(db_index=True, max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name': 'NETC Dispute',
                'verbose_name_plural': 'NETC Disputes',
            },
        ),
        migrations.CreateModel(
            name='NETCUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(db_index=True, max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('uptime_pct', models.FloatField()),
                ('incidents', models.IntegerField()),
                ('downtime_minutes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'NETC Uptime',
                'verbose_name_plural': 'NETC Uptimes',
            },
        ),
        migrations.CreateModel(
            name='RoadAccidentByCollision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('collision_type', models.CharField(max_length=100)),
                ('accidents', models.IntegerField(null=True)),
                ('killed', models.IntegerField(null=True)),
                ('injured', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Road Accident (Collision Type)',
                'verbose_name_plural': 'Road Accidents (Collision Types)',
            },
        ),
        migrations.CreateModel(
            name='RoadAccidentByRoadUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('road_user_type', models.CharField(max_length=100)),
                ('killed', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Road Accident (Road User)',
                'verbose_name_plural': 'Road Accidents (Road Users)',
            },
        ),
        migrations.CreateModel(
            name='NationalHighway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nh_number', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('length_km', models.FloatField(blank=True, null=True)),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'National Highway',
                'verbose_name_plural': 'National Highways',
                'indexes': [models.Index(fields=['nh_number'], name='insights_na_nh_numb_8c09b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NETCProcessingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toll_plaza_id', models.CharField(db_index=True, max_length=50)),
                ('plaza_name', models.CharField(max_length=255)),
                ('plaza_type', models.CharField(max_length=50)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('pct_within_2min', models.FloatField()),
            ],
            options={
                'verbose_name': 'NETC Processing Rate',
                'verbose_name_plural': 'NETC Processing Rates',
                'indexes': [models.Index(fields=['toll_plaza_id', 'fiscal_year'], name='insights_ne_toll_pl_046910_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoadAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_traffic_violation', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('source', models.CharField(default='MoRTH', max_length=50)),
            ],
            options={
                'verbose_name': 'Road Accident',
                'verbose_name_plural': 'Road Accidents',
                'indexes': [models.Index(fields=['year', 'state'], name='insights_ro_year_1738ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoadStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('road_category', models.CharField(max_length=100)),
                ('road_property', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='value in Kilometer', max_length=50)),
            ],
            options={
                'verbose_name': 'Road Statistic',
                'verbose_name_plural': 'Road Statistics',
                'indexes': [models.Index(fields=['year', 'road_category'], name='insights_ro_year_e55fd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TollPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaza_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plaza_type', models.CharField(choices=[('National', 'National'), ('State', 'State')], default='National', max_length=50)),
            ],
            options={
                'verbose_name': 'Toll Plaza',
                'verbose_name_plural': 'Toll Plazas',
                'indexes': [models.Index(fields=['state', 'plaza_type'], name='insights_to_state_97e2c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FASTagTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(db_index=True, max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('vehicle_count', models.BigIntegerField()),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='insights.tollplaza')),
            ],
            options={
                'verbose_name': 'FASTag Transaction',
                'verbose_name_plural': 'FASTag Transactions',
                'indexes': [models.Index(fields=['plaza', 'fiscal_year'], name='insights_fa_plaza_i_811f1f_idx')],
            },
        ),
    ]
