# Generated by Django 5.2.13 on 2026-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_economicsurvey_netcdispute_netcuptime_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='congestionlog',
            index=models.Index(fields=['lat', 'lng'], name='insights_co_lat_5fbb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='congestionlog',
            index=models.Index(fields=['location_name'], name='insights_co_locatio_3e4731_idx'),
        ),
    ]
